#  syntax=docker/dockerfile:1
FROM node:lts-alpine AS builder

WORKDIR /app
COPY . .

RUN yarn install

RUN yarn build

FROM node:lts-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/next.config.mjs ./next.config.mjs
COPY --from=builder /app/tailwind.config.ts ./tailwind.config.ts
COPY --from=builder /app/postcss.config.mjs ./postcss.config.mjs
COPY --from=builder /app/tsconfig.json ./tsconfig.json

COPY --from=builder /app/app ./app
COPY --from=builder /app/app/components ./components
COPY --from=builder /app/app/constants ./constants
COPY --from=builder /app/app/posts ./posts
COPY --from=builder /app/app/actions ./actions
COPY --from=builder /app/app/types ./types

EXPOSE 3000

CMD ["yarn", "start"]